server {
  port = 8080
  port = ${?SERVER_PORT}
}

kafka {
  bootstrapServers = "localhost:9092"
  bootstrapServers = ${?KAFKA_BOOTSTRAP_SERVERS}

  consumerGroup = "streamvault-pipeline"
  consumerGroup = ${?KAFKA_CONSUMER_GROUP}

  topics {
    mediaUploaded    = "media.uploaded"
    mediaUploaded    = ${?KAFKA_TOPIC_MEDIA_UPLOADED}

    mediaUploadedDlq = "media.uploaded.dlq"
    mediaUploadedDlq = ${?KAFKA_TOPIC_MEDIA_UPLOADED_DLQ}

    metadataReady    = "media.metadata-ready"
    metadataReady    = ${?KAFKA_TOPIC_METADATA_READY}

    transcoded       = "media.transcoded"
    transcoded       = ${?KAFKA_TOPIC_TRANSCODED}

    watchSyncRequested = "watch.sync-requested"
    watchSyncRequested = ${?KAFKA_TOPIC_WATCH_SYNC_REQUESTED}
  }
}
