kafka {
  bootstrapServers = "localhost:9092"
  bootstrapServers = ${?KAFKA_BOOTSTRAP_SERVERS}

  consumerGroup = "streamvault-pipeline"
  consumerGroup = ${?KAFKA_CONSUMER_GROUP}

  topics {
    mediaUploaded = "media.uploaded"
    mediaUploaded = ${?KAFKA_TOPIC_MEDIA_UPLOADED}

    watchSyncRequested = "watch.sync-requested"
    watchSyncRequested = ${?KAFKA_TOPIC_WATCH_SYNC_REQUESTED}
  }
}
